### ISSUE TITLE
RTD integration (readthedocs)

### ISSUE THREAD

**Issue by bburan** [LABSN/tdtpy#10]
Latest commits should fix RTD integration. Also fixed settings on the RTD side. However, I seem to need to manually trigger builds. I don't think I have sufficient privileges on this repo to enable commit hooks. I gave you maintainer access to the TDTPy RTD page (https://tdtpy.readthedocs.io/en/latest/). Do you mind checking to see if you can enable post-commit build triggers? Either case, RTD now shows the latest version and I added you as a contributor. If there's anyone else that deserves credit, please go ahead and add them or let me know.

**Comment by larsoner** [comment]
Bumped you up to admin so that hopefully you can do it @bburan . I have almost no RTD experience so I'm happy to let you try :) If you still can't do it I can take a look.

**Comment by bburan** [comment]
@larsoner Thanks! It required config on both RTD and GH, but all set now.
