### ISSUE TITLE
Fix Zenodo authors

### ISSUE THREAD

**Issue by bburan** [LABSN/tdtpy#11]
I created a new release that automatically updated the Zenodo records with a DOI for that release. However, it seems that I do not have privileges to edit the record. I think it has to do with my privileges on the LABSN account. The simplest solution is for someone with sufficient privileges (e.g., @larsoner) to fix the record to remove "buranconsult" from the authors list. Would someone mind doing this, please? Thanks! Going forward, we might want to consider creating a new organization (e.g., tdtpy) such that the Github URL Is https://github.com/tdtpy/tdtpy that way we can ensure maintainers have appropriate privileges. I believe this is a common approach for many community projects.

**Comment by larsoner** [comment]
> The simplest solution is for someone with sufficient privileges (e.g., @larsoner) to fix the record to remove "buranconsult" from the authors list. 

Done. I suspect the way to avoid it in the future would be with appropriate `.mailmap` entry and/or GitHub config changes on your end, not sure...

> Going forward, we might want to consider creating a new organization (e.g., tdtpy) such that the Github URL Is https://github.com/tdtpy/tdtpy that way we can ensure maintainers have appropriate privileges. I believe this is a common approach for many community projects.

Feel free to do this and I can transfer the repo

**Comment by bburan** [comment]
I will look into `.mailmap`. It occurred to me that moving the repository URL may break GH integration with Zenodo. I tried to get them to help me link an existing (manually created repository) to GH but they said I couldn't do that. So, it seems their interface has some limitations that may be difficult to deal with. For now, I'll close this issue. The main goal was to get the citations updated for a grant I'm submitting. Thanks, @larsoner for your quick help!
