### ISSUE TITLE
TODO: Make a maintenance release

### ISSUE THREAD

**Issue by Eric89GXL** [LABSN/tdtpy#6]
@wronk @lkishline any interest in learning how to make a software release? We should release a maintenance version of TDTpy (0.7.1 or whatever), and it would be a good learning experience if you're curious about how to do it.

**Comment by Eric89GXL** [comment]
Of course I'm happy to do it if you have other things going on.

**Comment by wronk** [comment]
Let's talk about it in person. I'm interested if it's not going to require a ton of time.

**Comment by lkishline** [comment]
My thoughts are the same as Marks.

**Comment by Eric89GXL** [comment]
If all goes well, I'd estimate an hour or two. We can adapt it from here, we'd need probably half of these steps:

https://github.com/mne-tools/mne-python/wiki/How-to-make-a-release

If one of you wants to do it, we can go through the list and adapt it for this repo. @drammock did you make a list for the `expyfun` release you did?

**Comment by wronk** [comment]
I'm definitely willing to help out if it's anywhere close to that amount of time.

**Comment by Eric89GXL** [comment]
@lkishline you want to challenge Mark for it? I have a coin I can flip.

**Comment by lkishline** [comment]
Ha! I'll let Mark have it this time round. But I would like to learn so I'd like to be in the loop.

**Comment by Eric89GXL** [comment]
Sure thing, @wronk we can work on it on Monday or Tuesday of next week, and come up with a wiki entry. @lkishline we could probably stand to do an expyfun release soon, too, so you could then do that one.

**Comment by wronk** [comment]
Sure, that would work. 

@lkishline, feel totally free to take this if you want to though.

**Comment by Eric89GXL** [comment]
@wronk see how far you can get with this tomorrow:

https://github.com/LABSN/tdtpy/wiki/How-to-make-a-release

To make a release I have to give you ownership permissions to the repo, so do me a solid and don't break anything okay?

**Comment by Eric89GXL** [comment]
@wronk I added you as "admin" not "owner", you can probably release with that permission level. If you don't have the option to add a release here, it means I'll have to bump you up again:

https://github.com/LABSN/tdtpy/releases

**Comment by wronk** [comment]
I don't see it as an option on that page...

**Comment by Eric89GXL** [comment]
Try again, I changed your permissions (might or might not work)

**Comment by Eric89GXL** [comment]
Also, I need your PyPi username if it's not `wronk`

**Comment by wronk** [comment]
I just made an account (`wronk`).

Yep, thanks. Permissions work now.

**Comment by Eric89GXL** [comment]
Added you on PyPi, hopefully you can edit things. Please update the little bit of docs while you're in there, I think it still has the old website and license (we are now BSD).

Also, the Zenodo badge should be available, track it down and add it to the README.rst (and add this step to the instructions)

**Comment by wronk** [comment]
Sounds good.

For the third bullet on the tdtpy wiki, should I make PRs for each of those small changes concerning the version?

**Comment by Eric89GXL** [comment]
You can just do them directly in `master`, they should be straightforward

**Comment by Eric89GXL** [comment]
... and in `maint/0.7.1`

**Comment by wronk** [comment]
Version 0.7.2 is up on PyPI :)

close
