### ISSUE TITLE
New PyPI release

### ISSUE THREAD

**Issue by bburan** [LABSN/tdtpy#9]
Perhaps bump to 0.8.0 since this adds a new feature (incremential/continuous writes)? I'm not picky about version though.

I can roll the release since I still have access to the PyPI project. Would you like me to do it?

**Comment by larsoner** [comment]
@bburan yes I would change version to `0.8.0`, push to PyPi using `twine`, then bump to `0.9.0.dev0` on `master`. I gave you maintainer access to the repo so feel free to do it if you're comfortable, otherwise I can do it early next week

**Comment by bburan** [comment]
What do you mean by bump to `0.9.0.dev0` on master?

**Comment by drammock** [comment]
@bburan after releasing on pypi, change [this line](https://github.com/LABSN/tdtpy/blob/master/tdt/__init__.py#L20)

**Comment by bburan** [comment]
@drammock I was not aware there was a version string embedded in `__init__.py` (perhaps I put it there and forgot about it). Thanks for pointing it out. I only edited the version in `setup.py` and released it on PyPI. We should get a new version pushed. What's the correct approach? `0.8.0.post0`?

**Comment by bburan** [comment]
When adding `0.8.0.post0` as a release, we would keep `__version__` at `0.8.0`?

Also, any thoughts on implementing this? Would be good to have a single place for build/version number. https://stackoverflow.com/questions/2058802/how-can-i-get-the-version-defined-in-setup-py-setuptools-in-my-package

**Comment by drammock** [comment]
> (perhaps I put it there and forgot about it)

`git blame` shows that @larsoner added it :)

> Would be good to have a single place for build/version number

MNE-Python (the project I'm most familiary with) does this by storing version number only in `__init__.py` and by reading that from `setup.py`, see [here](https://github.com/mne-tools/mne-python/blob/master/setup.py#L11-L19)

> What's the correct approach? `0.8.0.post0`?

I'm actually not all that familiar with pypi release version conventions, so IDK if `post0` is the right postfix or if it makes sense to bump to 0.8.1 for something this trivial (@larsoner?).  In any event I think the right steps are (1) change version string in `__init__.py` to something not including `dev0`, (2) change `setup.py` accordingly, (3) re-release on pypi, (4) change `__init__.py` to have version `0.9.0.dev0`

**Comment by larsoner** [comment]
I would release a `0.8.1` on PyPi with the fixed `__version__`

**Comment by bburan** [comment]
@drammock @larsoner Got it. Thanks! Will emulate MNE-Python's approach and take care of this when I get a chance.
